object frmMsg: TfrmMsg
  Left = 0
  Top = 0
  BorderIcons = []
  BorderStyle = bsToolWindow
  ClientHeight = 141
  ClientWidth = 556
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object Label1: TLabel
    Left = 0
    Top = 0
    Width = 556
    Height = 48
    Align = alTop
    Alignment = taCenter
    AutoSize = False
    Caption = #36664#20837#24037#21934#36039#35338
    Color = clTeal
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -43
    Font.Name = #27161#26999#39636
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Transparent = False
    ExplicitLeft = -8
    ExplicitTop = -9
    ExplicitWidth = 551
  end
  object plWOInfo: TPanel
    Left = 0
    Top = 48
    Width = 556
    Height = 95
    Align = alTop
    Color = clWhite
    ParentBackground = False
    TabOrder = 0
    object Panel39: TPanel
      Left = 1
      Top = 0
      Width = 554
      Height = 47
      Align = alBottom
      Color = clCream
      ParentBackground = False
      TabOrder = 0
      object edtSetWorkOrderNumber: TEdit
        Left = 217
        Top = 1
        Width = 336
        Height = 45
        Align = alClient
        Alignment = taCenter
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlue
        Font.Height = -37
        Font.Name = 'Times New Roman'
        Font.Style = []
        ImeMode = imSAlpha
        ParentFont = False
        TabOrder = 0
        Text = '000-00000000000'
        OnExit = edtSetWorkOrderNumberExit
        OnKeyDown = edtSetWorkOrderNumberKeyDown
        ExplicitHeight = 50
      end
      object Panel40: TPanel
        Left = 1
        Top = 1
        Width = 216
        Height = 45
        Align = alLeft
        Caption = #24037#21934' Work Order'
        Color = clGradientActiveCaption
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -20
        Font.Name = #27161#26999#39636
        Font.Style = []
        ParentBackground = False
        ParentFont = False
        TabOrder = 1
      end
    end
    object Panel5: TPanel
      Left = 1
      Top = 47
      Width = 554
      Height = 47
      Align = alBottom
      Color = clCream
      ParentBackground = False
      TabOrder = 1
      object edtSetEmployeeID: TEdit
        Left = 217
        Top = 1
        Width = 214
        Height = 45
        Align = alClient
        Alignment = taCenter
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlue
        Font.Height = -37
        Font.Name = 'Times New Roman'
        Font.Style = []
        ImeMode = imSAlpha
        ParentFont = False
        TabOrder = 0
        Text = 'T00000'
        OnExit = edtSetEmployeeIDExit
        OnKeyDown = edtSetEmployeeIDKeyDown
        ExplicitHeight = 50
      end
      object btnID_ok: TBitBtn
        Left = 431
        Top = 1
        Width = 122
        Height = 45
        Align = alRight
        Caption = 'OK'
        DoubleBuffered = True
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -33
        Font.Name = #27161#26999#39636
        Font.Style = []
        ParentDoubleBuffered = False
        ParentFont = False
        TabOrder = 1
        OnClick = btnID_okClick
      end
      object Panel41: TPanel
        Left = 1
        Top = 1
        Width = 216
        Height = 45
        Align = alLeft
        Caption = #24037#34399' Employee ID'
        Color = clSkyBlue
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -20
        Font.Name = #27161#26999#39636
        Font.Style = []
        ParentBackground = False
        ParentFont = False
        TabOrder = 2
      end
    end
    object Panel4: TPanel
      Left = 1
      Top = 1
      Width = 554
      Height = 0
      Align = alTop
      Color = clHighlightText
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -24
      Font.Name = #27161#26999#39636
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 2
      object Panel7: TPanel
        Left = 1
        Top = 1
        Width = 552
        Height = 46
        Align = alClient
        TabOrder = 0
        object ckbWIP: TPanel
          Left = 1
          Top = 1
          Width = 65
          Height = 44
          Align = alLeft
          Caption = #8730
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -33
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
        end
        object Panel8: TPanel
          Left = 346
          Top = 1
          Width = 207
          Height = 44
          Align = alLeft
          Caption = #25104#28204' FGI'
          Color = clMoneyGreen
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -24
          Font.Name = #27161#26999#39636
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
        end
        object ckbFGI: TPanel
          Left = 281
          Top = 1
          Width = 65
          Height = 44
          Align = alLeft
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -33
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 2
        end
        object Panel10: TPanel
          Left = 66
          Top = 1
          Width = 215
          Height = 44
          Align = alLeft
          Caption = #21322#28204' WIP'
          Color = clMoneyGreen
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -24
          Font.Name = #27161#26999#39636
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 3
        end
      end
    end
  end
  object TouchKeyboard: TTouchKeyboard
    Left = 0
    Top = 151
    Width = 556
    Height = 180
    Align = alTop
    GradientEnd = clSilver
    GradientStart = clGray
    Layout = 'Standard'
  end
  object plSwitch: TPanel
    Left = 0
    Top = 143
    Width = 556
    Height = 8
    Align = alTop
    Caption = 'V'
    Color = clHighlight
    ParentBackground = False
    TabOrder = 2
    OnClick = plSwitchClick
  end
end
